#### general settings
name: ediffsr2x_mod
use_tb_logger: true
model: denoising
distortion: sr
gpu_ids: [0,1,2,3] #,4,5,6,7]

sde:
  max_sigma: 50
  T: 100
  schedule: cosine # linear, cosine
  eps: 0.005

degradation: # for some synthetic dataset that only have GTs
  # for denoising
  sigma: 25
  noise_type: G # Gaussian noise: G

  # for super-resolution
  scale: 2
  
#### datasets
datasets:
  train:
    optimizer: AdamW # Adam, AdamW, Lion
    name: Train_Dataset
    mode: LQGT
    dataroot_GT: /trinity/home/m.aleshin/projects/superresolution/datasets/all/train
    scale_list: [0.2, 0.25, 0.33334, 0.4, 0.5, 0.66667, 1] # new param

    use_shuffle: true
    n_workers: 8  # per GPU
    batch_size: 64 # 
    GT_size: 256
    LR_size: 128
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: Val_Dataset
    mode: LQGT
    dataroot_GT: /trinity/home/m.aleshin/projects/superresolution/datasets/all/val/hr2m
    dataroot_LQ: /trinity/home/m.aleshin/projects/superresolution/datasets/all/val/lr4m
    n_workers: 8
    batch_size: 64


#### network structures
network_G:
  which_model_G: ConditionalNAFNet
  setting:
    width: 32
    enc_blk_nums: [8, 1, 1, 1]
    middle_blk_num: 1
    dec_blk_nums: [1, 1, 1, 1]

#### path
path:
  pretrain_model_G: /trinity/home/m.aleshin/projects/superresolution/EDiffSR/experiments/sisr/ediffsr2x_mod/models/120000_G.pth
  strict_load: true
  resume_state: /trinity/home/m.aleshin/projects/superresolution/EDiffSR/experiments/sisr/ediffsr2x_mod/training_state/120000.state

#### training settings: learning rate scheme, loss
train:
  optimizer: AdamW # Adam, AdamW, Lion
  lr_G: !!float 4e-5
  lr_scheme: TrueCosineAnnealingLR
  beta1: 0.9
  beta2: 0.99
  niter: 500000 # 700000
  warmup_iter: -1  # no warm up
  lr_steps: [100000, 200000, 300000] # [200000, 300000, 400000]
  lr_gamma: 0.5
  eta_min: !!float 1e-7

  # criterion
  is_weighted: False
  loss_type: l1
  weight: 1.0

  manual_seed: 0
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
